# Generated by Django 4.0 on 2021-12-07 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursemodel',
            name='VaccineCenterModel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.vaccinecentermodel'),
        ),
        migrations.AddField(
            model_name='slotmodel',
            name='nurse',
            field=models.ManyToManyField(related_name='nurse_of_slot', to='api.NurseModel'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='VaccineCenterModel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.vaccinecentermodel'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.nursemodel'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.slotmodel'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='vaccine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.vaccinemodel'),
        ),
    ]
