# Generated by Django 4.0 on 2021-12-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_nursemodel_vaccinecentermodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotmodel',
            name='nurse',
            field=models.ManyToManyField(blank=True, default=None, related_name='nurse_of_slot', to='api.NurseModel'),
        ),
    ]
