# Generated by Django 3.2.9 on 2021-12-08 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_usermodel_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nursemodel',
            old_name='VaccineCenterModel',
            new_name='vaccineCenter',
        ),
    ]
