# Generated by Django 3.2.9 on 2021-12-08 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_vaccinecentermodel_nursemodel_vaccinecenter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='VaccineCenterModel',
            new_name='vaccineCenter',
        ),
    ]
