# Generated by Django 4.0 on 2021-12-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_vaccinecentermodel_usermodel_vaccinecenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursemodel',
            name='password',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
